-- Vimwiki
-- vim.g.vimwiki_table_mappings = 0
-- vim.g.vimwiki_list = {{
--     path = '~/docs/uni/notes/',
--     path_html = '~/docs/uni/notes/html',
--     syntax = 'markdown',
--     ext = '.md'
-- }}
-- vim.g.vimwiki_url_maxsave = 0
